<?= $this->doctype() ?>

<html>
    <head>
        <meta charset="utf-8">
        <script data-main="js/app/main" src="js/require.js"></script>    </head>
        <?= $this->headTitle('DecSoft')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
    </head>
    <body ng-controller="MainController">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" ng-controller="MenuController">
            <div class="container" menu-directive="MenuContent">
                <?= $this->partial("layout/menu/main.phtml");?>
            </div>
        </nav>
        <div class="container">
            <div class="row" main-page-directive="MainPageContent">
            <?= $this->content ?>
            </div>
<!--            <div class="row">
                <footer>
                    <hr>
                    <p>2017 By Peyman Mostafai Ekhtiar. ( version = <?php // \Application\Module::VERSION ?> )</p>
                </footer>
            </div>-->
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
