<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<?= $this->url('root') ?>">
        &nbsp;DecSoft
    </a>
</div>
<?php 
if (!is_null($this->identity())){ ?>
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li>
            <a href="#" ng-click="getForm('<?= $this->url('phonebook') ?>')">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            </a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#" ng-click="getForm('<?= $this->url('phonebook',['action' => 'manage'])?>')"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add</a></li>
                </ul>
         </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#"> (<?= $this->identity()->getFullName()?>)</a></li>
        <li><a href="#" ng-click="getForm('<?= $this->url('root',['action' => 'register', 'isEdit' => 1])?>')">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
        </li>
        <li><a href="<?= $this->url('root',['action' => 'logout']) ?>">
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a>
        </li>
    </ul>
</div>
<?php } else {?>
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#" ng-click="getForm('<?= $this->url('root', ['action' => 'register']) ?>')">
            Register</a>
        </li>
        <li><a href="#" ng-click="getForm('<?= $this->url('root', ['action' => 'login']) ?>')">
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span></a>
        </li>
    </ul>
</div>
<?php } ?>
