<div class="panel panel-default text-center" ng-controller="LoginController">
    <div ng-init="getMenu('<?= $this->url('root',['action' => 'menu'])?>')"></div>
    <?php if (!is_null($this->identity())){ ?>
        <div ng-init="redirect('<?=$this->url('phonebook')?>')"></div>
    <?php } else {?>
        <div class="panel-heading">
          <h3 class="panel-title">Login</h3>
        </div>
        <div class="panel-body">
          <section id="loginFormSection">
                <form ng-submit="submit('<?=$this->url('root',array('action'=>'login'))?>')" class="form-horizontal" id="loginForm">
                    <div class="form-group">
                       <input ng-model="User.Email" name="Email" id="Email" type="email" class="form-control" placeholder="Email" ng-init="User.Email='<?= $form->get('Email')->getValue()?>'"/>
                        <?=  $this->formElementErrors($form->get('Email')); ?> 
                    </div>
                    <div class="form-group">
                       <input ng-model="User.Password" name="Password" id="Password" type="Password" class="form-control" placeholder="Password" ng-init="User.Password='<?= $form->get('Password')->getValue()?>'"/>
                        <?= $this->formElementErrors($form->get('Password')); ?> 
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary" />
                    </div>
                    <?php if (isset($message)){
                        echo $this->partial("error/_alert.phtml", ["typeAlert" => "info", "message" => $message]);  
                     }?> 
                </form>
          </section><!-- content -->
        </div>
    <?php }?>
</div>
