<div class="panel panel-default text-center" ng-controller="RegisterController">
  <div class="panel-heading">
      <h3 class="panel-title">Register</h3>
  </div>
  <div class="panel-body">
    <section id="loginFormSection">
        <form ng-submit="submit('<?=$this->url('root',array('action'=>'register'))?>')" class="form-horizontal" id="registerForm">
            <input ng-model="User.id" name="id" id="id" type='hidden' ng-init="User.id='<?= $form->get('id')->getValue()?>'"/>
           <div class="form-group">
               <input ng-model="User.FirstName" name="FirstName" id="FirstName" type="text" class="form-control" placeholder="First name" ng-init="User.FirstName='<?= $form->get('FirstName')->getValue()?>'"/>
                <?= $this->formElementErrors($form->get('FirstName')); ?> 
            </div>
           <div class="form-group">
               <input ng-model="User.LastName" name="LastName" id="LastName" type="text" class="form-control" placeholder="Last name" ng-init="User.LastName='<?= $form->get('LastName')->getValue()?>'"/>
               <?= $this->formElementErrors($form->get('LastName')); ?> 
            </div>
           <div class="form-group">
               <input ng-model="User.Email" name="Email" id="Email" type="email" class="form-control" placeholder="Email" ng-init="User.Email='<?= $form->get('Email')->getValue()?>'"/>
                <?= $this->formElementErrors($form->get('Email')); ?> 
            </div>
           <div class="form-group">
               <input ng-model="User.Password" name="Password" id="Password" type="Password" class="form-control" placeholder="Password"/>
                <?= $this->formElementErrors($form->get('Password')); ?> 
            </div>
           <div class="form-group">
               <input ng-model="User.repassword" name="repassword" id="repassword" type="Password" class="form-control" placeholder="Retype password"/>
                <?= $this->formElementErrors($form->get('repassword')); ?> 
            </div>
            <div class="form-group">
                <input type="submit" value="<?= $valueButton?>" class="btn btn-primary" />
            </div>
            <?php if (isset($message)){?>
                <?= $this->partial("error/_alert.phtml", ["typeAlert" => "info", "message" => $message]); ?>   
            <?php } ?>
        </form>
    </section><!-- content -->
  </div>
</div>